import React from "react";
import {
  AbsoluteFill,
  interpolate,
  useCurrentFrame,
  Easing,
} from "remotion";
import { C } from "../brand/colors";
import { FONTS } from "../brand/fonts";
import { GrainOverlay } from "../brand/GrainOverlay";
import { Timecode } from "../brand/Timecode";
import { Logo } from "../brand/Logo";

// 23 - 29s | 690 - 870 frames
// Two social posts side by side: Twitter (left) and LinkedIn (right).
// Both announce the dark mode release. Both generated by Patchwork.
export const SocialPosts: React.FC = () => {
  const frame = useCurrentFrame();

  const fadeOut = interpolate(frame, [170, 180], [1, 0], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  // Twitter card slides in from left
  const twitterIn = interpolate(frame, [4, 36], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.22, 1, 0.36, 1),
  });
  const twitterX = interpolate(frame, [4, 36], [-60, 0], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.22, 1, 0.36, 1),
  });

  // LinkedIn slides in from right
  const linkedIn = interpolate(frame, [16, 48], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.22, 1, 0.36, 1),
  });
  const linkedX = interpolate(frame, [16, 48], [60, 0], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.22, 1, 0.36, 1),
  });

  // Engagement numbers tick up
  const likeProgress = interpolate(frame, [60, 110], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.45, 0, 0.55, 1),
  });

  const tweet = `🚀 v2.4.0 is live.

dark mode is finally here. 🌙

toggle it from
Settings → Appearance.

built it in 6 days. open to feedback.

#buildinpublic #indiehackers`;

  const linkedinBody = `Excited to ship v2.4.0 — dark mode is finally live.

After 3 months of user requests, we rebuilt our theming system from scratch. Every component now ships with both light and dark variants, and the preference respects your OS settings automatically.

→ Settings → Appearance → Theme
→ Works on web, iOS, and Android (rolling out tonight)

Thanks to the 200+ folks who upvoted this on the roadmap. You shaped the spec.

What's next: user-defined accent colors. Voting open now.`;

  // Typing animation — Twitter (chars reveal)
  const tweetChars = Math.min(
    tweet.length,
    Math.floor(interpolate(frame, [40, 100], [0, tweet.length], {
      extrapolateLeft: "clamp",
      extrapolateRight: "clamp",
    }))
  );

  // LinkedIn — paragraph-by-paragraph reveal
  const liParas = linkedinBody.split("\n\n");
  const liVisible = liParas.filter((_, i) => frame >= 56 + i * 10).length;

  return (
    <AbsoluteFill
      style={{
        background: C.ink,
        padding: "36px 48px",
        opacity: fadeOut,
        flexDirection: "column",
      }}
    >
      <GrainOverlay opacity={0.05} />

      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: 16,
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
          <Timecode label="TC" fps={30} />
          <span
            style={{
              fontFamily: FONTS.mono,
              fontSize: 11,
              color: C.mute,
              letterSpacing: "0.18em",
            }}
          >
            · DISTRIBUTION · SOCIAL DRAFTS
          </span>
        </div>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 8,
            fontFamily: FONTS.mono,
            fontSize: 11,
            color: C.amber,
            letterSpacing: "0.18em",
          }}
        >
          <Logo size={16} glow={false} />
          DRAFTED BY PATCHWORK
        </div>
      </div>

      <div
        style={{
          fontFamily: FONTS.mono,
          fontSize: 11,
          color: C.amber,
          letterSpacing: "0.22em",
          marginBottom: 8,
        }}
      >
        · AUTO-DISTRIBUTED
      </div>
      <div
        style={{
          fontFamily: FONTS.display,
          fontWeight: 900,
          fontSize: 44,
          color: C.paper,
          letterSpacing: "-0.035em",
          lineHeight: 1,
          marginBottom: 18,
          fontVariationSettings: '"opsz" 144, "SOFT" 30, "WONK" 0',
        }}
      >
        One release.{" "}
        <span style={{ color: C.amber, fontStyle: "italic", fontWeight: 400 }}>
          Everywhere
        </span>{" "}
        it matters.
      </div>

      <div
        style={{
          flex: 1,
          display: "grid",
          gridTemplateColumns: "1fr 1.2fr",
          gap: 18,
          minHeight: 0,
        }}
      >
        {/* TWITTER / X CARD */}
        <div
          style={{
            opacity: twitterIn,
            transform: `translateX(${twitterX}px)`,
            background: C.charcoal,
            border: `1px solid ${C.line}`,
            padding: 18,
            display: "flex",
            flexDirection: "column",
            overflow: "hidden",
          }}
        >
          {/* Twitter header bar */}
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              paddingBottom: 12,
              borderBottom: `1px solid ${C.line}`,
              marginBottom: 14,
            }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 8,
                fontFamily: FONTS.display,
                fontWeight: 900,
                fontSize: 22,
                color: C.paper,
                letterSpacing: "-0.04em",
                fontVariationSettings: '"opsz" 144',
              }}
            >
              <XLogo />
              post
            </div>
            <span
              style={{
                fontFamily: FONTS.mono,
                fontSize: 9,
                color: C.amber,
                letterSpacing: "0.2em",
              }}
            >
              · DRAFT
            </span>
          </div>

          {/* Author */}
          <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
            <div
              style={{
                width: 44,
                height: 44,
                borderRadius: "50%",
                background: C.amber,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                fontFamily: FONTS.display,
                fontWeight: 900,
                fontSize: 18,
                color: C.ink,
                fontVariationSettings: '"opsz" 144',
              }}
            >
              P
            </div>
            <div style={{ display: "flex", flexDirection: "column" }}>
              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: 6,
                  fontFamily: FONTS.sans,
                  fontSize: 14,
                  fontWeight: 700,
                  color: C.paper,
                }}
              >
                Patchwork
                <VerifiedTick />
              </div>
              <div
                style={{
                  fontFamily: FONTS.mono,
                  fontSize: 11,
                  color: C.mute,
                }}
              >
                @patchwork_dev · 2m
              </div>
            </div>
          </div>

          {/* Tweet body */}
          <div
            style={{
              marginTop: 12,
              fontFamily: FONTS.sans,
              fontSize: 14,
              lineHeight: 1.5,
              color: C.paper,
              whiteSpace: "pre-wrap",
              flex: 1,
              minHeight: 0,
            }}
          >
            {tweet.slice(0, tweetChars)}
            {tweetChars < tweet.length && (
              <span
                style={{
                  display: "inline-block",
                  width: 7,
                  height: 14,
                  background: C.amber,
                  marginLeft: 2,
                  opacity: interpolate(frame % 12, [0, 6, 12], [1, 0, 1], {
                    extrapolateLeft: "clamp",
                    extrapolateRight: "clamp",
                  }),
                  transform: "translateY(1px)",
                }}
              />
            )}
          </div>

          {/* Engagement row */}
          <div
            style={{
              marginTop: 14,
              paddingTop: 12,
              borderTop: `1px solid ${C.line}`,
              display: "flex",
              gap: 18,
              fontFamily: FONTS.mono,
              fontSize: 10,
              color: C.mute,
              letterSpacing: "0.06em",
            }}
          >
            <Engage icon="💬" label="replies" count={Math.round(likeProgress * 47)} />
            <Engage icon="🔁" label="reposts" count={Math.round(likeProgress * 128)} />
            <Engage icon="♥" label="likes" count={Math.round(likeProgress * 612)} />
            <Engage icon="📊" label="views" count={Math.round(likeProgress * 12400)} />
          </div>
        </div>

        {/* LINKEDIN CARD */}
        <div
          style={{
            opacity: linkedIn,
            transform: `translateX(${linkedX}px)`,
            background: C.charcoal,
            border: `1px solid ${C.line}`,
            padding: 18,
            display: "flex",
            flexDirection: "column",
            overflow: "hidden",
          }}
        >
          {/* LinkedIn header bar */}
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              paddingBottom: 12,
              borderBottom: `1px solid ${C.line}`,
              marginBottom: 14,
            }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 8,
                fontFamily: FONTS.display,
                fontWeight: 900,
                fontSize: 22,
                color: C.paper,
                letterSpacing: "-0.04em",
                fontVariationSettings: '"opsz" 144',
              }}
            >
              <LinkedInLogo />
              post
            </div>
            <span
              style={{
                fontFamily: FONTS.mono,
                fontSize: 9,
                color: C.amber,
                letterSpacing: "0.2em",
              }}
            >
              · DRAFT
            </span>
          </div>

          {/* Author */}
          <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
            <div
              style={{
                width: 44,
                height: 44,
                borderRadius: 6,
                background: C.amber,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                fontFamily: FONTS.display,
                fontWeight: 900,
                fontSize: 18,
                color: C.ink,
                fontVariationSettings: '"opsz" 144',
              }}
            >
              P
            </div>
            <div style={{ display: "flex", flexDirection: "column" }}>
              <div
                style={{
                  fontFamily: FONTS.sans,
                  fontSize: 14,
                  fontWeight: 700,
                  color: C.paper,
                }}
              >
                Patchwork · The release reel platform
              </div>
              <div
                style={{
                  fontFamily: FONTS.mono,
                  fontSize: 10,
                  color: C.mute,
                  marginTop: 1,
                }}
              >
                2,847 followers
              </div>
              <div
                style={{
                  fontFamily: FONTS.mono,
                  fontSize: 10,
                  color: C.mute,
                }}
              >
                2m · 🌐
              </div>
            </div>
          </div>

          {/* Body */}
          <div
            style={{
              marginTop: 12,
              fontFamily: FONTS.sans,
              fontSize: 13,
              lineHeight: 1.55,
              color: C.paper,
              flex: 1,
              minHeight: 0,
              overflow: "hidden",
            }}
          >
            {liParas.slice(0, liVisible).map((p, i) => (
              <p key={i} style={{ marginBottom: 8 }}>
                {p}
              </p>
            ))}
            {liVisible < liParas.length && (
              <span
                style={{
                  display: "inline-block",
                  width: 7,
                  height: 13,
                  background: C.amber,
                  opacity: interpolate(frame % 12, [0, 6, 12], [1, 0, 1], {
                    extrapolateLeft: "clamp",
                    extrapolateRight: "clamp",
                  }),
                  transform: "translateY(1px)",
                }}
              />
            )}
          </div>

          {/* Hashtags */}
          {liVisible >= liParas.length && (
            <div
              style={{
                marginTop: 8,
                fontFamily: FONTS.sans,
                fontSize: 12,
                color: "#6B9BD2",
              }}
            >
              #ProductDevelopment #DevTools #BuildInPublic #DarkMode
            </div>
          )}

          {/* Engagement row */}
          <div
            style={{
              marginTop: 12,
              paddingTop: 12,
              borderTop: `1px solid ${C.line}`,
              display: "flex",
              gap: 18,
              fontFamily: FONTS.mono,
              fontSize: 10,
              color: C.mute,
              letterSpacing: "0.06em",
            }}
          >
            <Engage icon="👍" label="reactions" count={Math.round(likeProgress * 84)} />
            <Engage icon="💬" label="comments" count={Math.round(likeProgress * 12)} />
            <Engage icon="🔁" label="reposts" count={Math.round(likeProgress * 23)} />
          </div>
        </div>
      </div>

      <div
        style={{
          marginTop: 12,
          display: "flex",
          justifyContent: "space-between",
          fontFamily: FONTS.mono,
          fontSize: 10,
          color: C.mute,
          letterSpacing: "0.18em",
          opacity: 0.7,
        }}
      >
        <span>· 06 / 07 · DISTRIBUTION</span>
        <span style={{ color: C.amber }}>READY TO POST · ONE CLICK</span>
      </div>
    </AbsoluteFill>
  );
};

const Engage: React.FC<{ icon: string; label: string; count: number }> = ({
  icon,
  label,
  count,
}) => (
  <div style={{ display: "flex", alignItems: "center", gap: 5 }}>
    <span style={{ fontSize: 11 }}>{icon}</span>
    <span style={{ color: C.cream }}>{count.toLocaleString()}</span>
    <span style={{ opacity: 0.6 }}>{label}</span>
  </div>
);

const XLogo: React.FC = () => (
  <svg width="20" height="20" viewBox="0 0 24 24" fill={C.paper}>
    <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
  </svg>
);

const LinkedInLogo: React.FC = () => (
  <svg width="20" height="20" viewBox="0 0 24 24" fill={C.paper}>
    <path d="M20.45 20.45h-3.55v-5.57c0-1.33-.02-3.04-1.85-3.04-1.85 0-2.14 1.45-2.14 2.94v5.67H9.36V9h3.41v1.56h.05c.48-.9 1.64-1.85 3.37-1.85 3.6 0 4.27 2.37 4.27 5.46v6.28zM5.34 7.43a2.06 2.06 0 11.01-4.12 2.06 2.06 0 010 4.12zM7.12 20.45H3.56V9h3.56v11.45zM22.22 0H1.77C.8 0 0 .77 0 1.72v20.56C0 23.23.8 24 1.77 24h20.45c.97 0 1.78-.77 1.78-1.72V1.72C24 .77 23.19 0 22.22 0z" />
  </svg>
);

const VerifiedTick: React.FC = () => (
  <svg width="14" height="14" viewBox="0 0 24 24">
    <path
      d="M22.5 12.5L20.7 14.7L21 17.5L18.2 17.8L17 20.5L14.3 19.5L12 21L9.7 19.5L7 20.5L5.8 17.8L3 17.5L3.3 14.7L1.5 12.5L3.3 10.3L3 7.5L5.8 7.2L7 4.5L9.7 5.5L12 4L14.3 5.5L17 4.5L18.2 7.2L21 7.5L20.7 10.3L22.5 12.5Z"
      fill={C.amber}
    />
    <path
      d="M9 12.2L11 14.2L15 10.2"
      stroke={C.ink}
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      fill="none"
    />
  </svg>
);
